package sks_spider

// slow slow slow to fail
var BlacklistedHosts = map[string]bool{

	"pgp.srv.ualberta.ca":          true,
	"pgpkeys.logintas.ch":          true,
	"druzhnaya.canonical.com":      true,
	"honeynet.homelinux.com":       true,
	"oppie.homelinux.com":          true,
	"sks.teanfordhouse.com":        true,
	"keyserver.unixbyte.com":       true,
	"pgp.gabrix.ath.cx":            true,
	"gpg-keyserver.de":             true,
	"key-server.de":                true,
	"sks.mit.edu":                  true,
	"sks-server.siu.edu":           true,
	"keyserver.uz.sns.it":          true,
	"users.nayr.net":               true,
	"keyserver.nijkamp.net":        true,
	"keyserver.nyfnet.net":         true,
	"keyserver.vescudero.net":      true,
	"keyserver.mine.nu":            true,
	"key.adeti.org":                true,
	"key.space.chaos-disciple.org": true,
	"esd0.colliertech.org":         true,
	"keyserver.colliertech.org":    true,
	"pki.colliertech.org":          true,
	"cryptochan.org":               true,
	"redundant.dyndns.org":         true,
	"gpg.kalkulators.org":          true,
	"keyserver.mozilla.org":        true,
	"pgp.codelabs.ru":              true,
	"odin.stueve.us":               true,
	"orion.stueve.us":              true,
	"keyserver.ws":                 true,
	"alpha.keyserver.ws":           true,
	"delta.keyserver.ws":           true,
}
